networks:
  resource-private:
    driver: bridge
  backend-network:
    external: true

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-resource
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - resource-private
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    container_name: library-api
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - JWKS_URI=${JWKS_URI}
      - RESOURCE_SERVER_URL=${RESOURCE_SERVER_URL}
      - AUTH_SERVER_URL=${AUTH_SERVER_URL}
    volumes:
      - ~/.aws:/root/.aws:ro
    ports:
      - "8080:8080"
    networks:
      - backend-network
      - resource-private
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysqldata:
