spring:
  application:
    name: resource-server

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
