spring:
  application:
    name: resource-server

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev

app:
  aws:
    s3:
      book-key: "/book.pdf"
      cover-key: "/cover.png"
      preview-key: "/preview.pdf"
      url-duration-min: 5

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
