spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      region:
        static: ${AWS_S3_REGION}

app:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}

openapi:
  resource-server-url: ${DEV_RESOURCE_SERVER_URL}
  auth-server-url: ${DEV_AUTH_SERVER_URL}
  server-description: Development server
