spring:
  application:
    name: resource-server

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  aws:
    s3:
      book-key: "/book.pdf"
      cover-key: "/cover.png"
      preview-key: "/preview.pdf"
      url-duration-min: 5
