services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqlauthdata:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    container_name: auth-server
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
#    volumes:
#      - ~/.aws:/root/.aws:ro
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysqlauthdata: